model:
  name: Qwen3-VL-8B-Instruct
  base_url: 
  api_key: ""
  default_prompt: "请根据提供的网页设计图，编写对应的HTML代码，将结果写在一个 markdown HTML 代码块中"
  allowed_mime_types:
    - image/png
    - image/jpeg
    - image/svg+xml
  sampling_args:
    temperature: 0.7
    top_p: 0.8
    presence_penalty: 1.5
    max_completion_tokens: 16384
  extra_args:
    top_k: 20
    repetition_penalty: 1.0

openrouter:
  enabled: true
  api_key: ""
  base_url: "https://openrouter.ai/api/v1"
  default_sampling_args:
    temperature: 0.7
    max_tokens: 4096
  models:
    - name: "amazon/nova-lite-v1"
      display_name: "Amazon: Nova Lite 1.0"
    - name: "amazon/nova-premier-v1"
      display_name: "Amazon: Nova Premier 1.0"
    - name: "amazon/nova-pro-v1"
      display_name: "Amazon: Nova Pro 1.0"
    - name: "anthropic/claude-3-haiku"
      display_name: "Anthropic: Claude 3 Haiku"
    - name: "anthropic/claude-3-opus"
      display_name: "Anthropic: Claude 3 Opus"
    - name: "anthropic/claude-3.5-haiku"
      display_name: "Anthropic: Claude 3.5 Haiku"
    - name: "anthropic/claude-3.5-haiku-20241022"
      display_name: "Anthropic: Claude 3.5 Haiku (2024-10-22)"
    - name: "anthropic/claude-3.5-sonnet"
      display_name: "Anthropic: Claude 3.5 Sonnet"
    - name: "anthropic/claude-3.7-sonnet"
      display_name: "Anthropic: Claude 3.7 Sonnet"
    - name: "anthropic/claude-3.7-sonnet:thinking"
      display_name: "Anthropic: Claude 3.7 Sonnet (thinking)"
    - name: "anthropic/claude-haiku-4.5"
      display_name: "Anthropic: Claude Haiku 4.5"
    - name: "anthropic/claude-opus-4"
      display_name: "Anthropic: Claude Opus 4"
    - name: "anthropic/claude-opus-4.1"
      display_name: "Anthropic: Claude Opus 4.1"
    - name: "anthropic/claude-opus-4.5"
      display_name: "Anthropic: Claude Opus 4.5"
    - name: "anthropic/claude-sonnet-4"
      display_name: "Anthropic: Claude Sonnet 4"
    - name: "anthropic/claude-sonnet-4.5"
      display_name: "Anthropic: Claude Sonnet 4.5"
    - name: "arcee-ai/spotlight"
      display_name: "Arcee AI: Spotlight"
    - name: "baidu/ernie-4.5-vl-28b-a3b"
      display_name: "Baidu: ERNIE 4.5 VL 28B A3B"
    - name: "baidu/ernie-4.5-vl-424b-a47b"
      display_name: "Baidu: ERNIE 4.5 VL 424B A47B "
    - name: "openrouter/bert-nebulon-alpha"
      display_name: "Bert-Nebulon Alpha"
    - name: "bytedance/ui-tars-1.5-7b"
      display_name: "ByteDance: UI-TARS 7B "
    - name: "deepcogito/cogito-v2-preview-llama-109b-moe"
      display_name: "Cogito V2 Preview Llama 109B"
    - name: "google/gemini-2.0-flash-001"
      display_name: "Google: Gemini 2.0 Flash"
    - name: "google/gemini-2.0-flash-exp:free"
      display_name: "Google: Gemini 2.0 Flash Experimental (free)"
    - name: "google/gemini-2.0-flash-lite-001"
      display_name: "Google: Gemini 2.0 Flash Lite"
    - name: "google/gemini-2.5-flash"
      display_name: "Google: Gemini 2.5 Flash"
    - name: "google/gemini-2.5-flash-image"
      display_name: "Google: Gemini 2.5 Flash Image (Nano Banana)"
    - name: "google/gemini-2.5-flash-image-preview"
      display_name: "Google: Gemini 2.5 Flash Image Preview (Nano Banana)"
    - name: "google/gemini-2.5-flash-lite"
      display_name: "Google: Gemini 2.5 Flash Lite"
    - name: "google/gemini-2.5-flash-lite-preview-09-2025"
      display_name: "Google: Gemini 2.5 Flash Lite Preview 09-2025"
    - name: "google/gemini-2.5-flash-preview-09-2025"
      display_name: "Google: Gemini 2.5 Flash Preview 09-2025"
    - name: "google/gemini-2.5-pro"
      display_name: "Google: Gemini 2.5 Pro"
    - name: "google/gemini-2.5-pro-preview-05-06"
      display_name: "Google: Gemini 2.5 Pro Preview 05-06"
    - name: "google/gemini-2.5-pro-preview"
      display_name: "Google: Gemini 2.5 Pro Preview 06-05"
    - name: "google/gemini-3-pro-preview"
      display_name: "Google: Gemini 3 Pro Preview"
    - name: "google/gemma-3-12b-it"
      display_name: "Google: Gemma 3 12B"
    - name: "google/gemma-3-12b-it:free"
      display_name: "Google: Gemma 3 12B (free)"
    - name: "google/gemma-3-27b-it"
      display_name: "Google: Gemma 3 27B"
    - name: "google/gemma-3-27b-it:free"
      display_name: "Google: Gemma 3 27B (free)"
    - name: "google/gemma-3-4b-it"
      display_name: "Google: Gemma 3 4B"
    - name: "google/gemma-3-4b-it:free"
      display_name: "Google: Gemma 3 4B (free)"
    - name: "google/gemini-3-pro-image-preview"
      display_name: "Google: Nano Banana Pro (Gemini 3 Pro Image Preview)"
    - name: "meta-llama/llama-3.2-11b-vision-instruct"
      display_name: "Meta: Llama 3.2 11B Vision Instruct"
    - name: "meta-llama/llama-3.2-90b-vision-instruct"
      display_name: "Meta: Llama 3.2 90B Vision Instruct"
    - name: "meta-llama/llama-4-maverick"
      display_name: "Meta: Llama 4 Maverick"
    - name: "meta-llama/llama-4-scout"
      display_name: "Meta: Llama 4 Scout"
    - name: "meta-llama/llama-guard-4-12b"
      display_name: "Meta: Llama Guard 4 12B"
    - name: "microsoft/phi-4-multimodal-instruct"
      display_name: "Microsoft: Phi 4 Multimodal Instruct"
    - name: "minimax/minimax-01"
      display_name: "MiniMax: MiniMax-01"
    - name: "mistralai/mistral-medium-3"
      display_name: "Mistral: Mistral Medium 3"
    - name: "mistralai/mistral-medium-3.1"
      display_name: "Mistral: Mistral Medium 3.1"
    - name: "mistralai/mistral-small-3.1-24b-instruct"
      display_name: "Mistral: Mistral Small 3.1 24B"
    - name: "mistralai/mistral-small-3.1-24b-instruct:free"
      display_name: "Mistral: Mistral Small 3.1 24B (free)"
    - name: "mistralai/mistral-small-3.2-24b-instruct"
      display_name: "Mistral: Mistral Small 3.2 24B"
    - name: "mistralai/pixtral-12b"
      display_name: "Mistral: Pixtral 12B"
    - name: "mistralai/pixtral-large-2411"
      display_name: "Mistral: Pixtral Large 2411"
    - name: "nvidia/nemotron-nano-12b-v2-vl"
      display_name: "NVIDIA: Nemotron Nano 12B 2 VL"
    - name: "nvidia/nemotron-nano-12b-v2-vl:free"
      display_name: "NVIDIA: Nemotron Nano 12B 2 VL (free)"
    - name: "openai/chatgpt-4o-latest"
      display_name: "OpenAI: ChatGPT-4o"
    - name: "openai/codex-mini"
      display_name: "OpenAI: Codex Mini"
    - name: "openai/gpt-4-turbo"
      display_name: "OpenAI: GPT-4 Turbo"
    - name: "openai/gpt-4.1"
      display_name: "OpenAI: GPT-4.1"
    - name: "openai/gpt-4.1-mini"
      display_name: "OpenAI: GPT-4.1 Mini"
    - name: "openai/gpt-4.1-nano"
      display_name: "OpenAI: GPT-4.1 Nano"
    - name: "openai/gpt-4o"
      display_name: "OpenAI: GPT-4o"
    - name: "openai/gpt-4o-2024-05-13"
      display_name: "OpenAI: GPT-4o (2024-05-13)"
    - name: "openai/gpt-4o-2024-08-06"
      display_name: "OpenAI: GPT-4o (2024-08-06)"
    - name: "openai/gpt-4o-2024-11-20"
      display_name: "OpenAI: GPT-4o (2024-11-20)"
    - name: "openai/gpt-4o:extended"
      display_name: "OpenAI: GPT-4o (extended)"
    - name: "openai/gpt-4o-mini"
      display_name: "OpenAI: GPT-4o-mini"
    - name: "openai/gpt-4o-mini-2024-07-18"
      display_name: "OpenAI: GPT-4o-mini (2024-07-18)"
    - name: "openai/gpt-5"
      display_name: "OpenAI: GPT-5"
    - name: "openai/gpt-5-chat"
      display_name: "OpenAI: GPT-5 Chat"
    - name: "openai/gpt-5-codex"
      display_name: "OpenAI: GPT-5 Codex"
    - name: "openai/gpt-5-image"
      display_name: "OpenAI: GPT-5 Image"
    - name: "openai/gpt-5-image-mini"
      display_name: "OpenAI: GPT-5 Image Mini"
    - name: "openai/gpt-5-mini"
      display_name: "OpenAI: GPT-5 Mini"
    - name: "openai/gpt-5-nano"
      display_name: "OpenAI: GPT-5 Nano"
    - name: "openai/gpt-5-pro"
      display_name: "OpenAI: GPT-5 Pro"
    - name: "openai/gpt-5.1"
      display_name: "OpenAI: GPT-5.1"
    - name: "openai/gpt-5.1-chat"
      display_name: "OpenAI: GPT-5.1 Chat"
    - name: "openai/gpt-5.1-codex"
      display_name: "OpenAI: GPT-5.1-Codex"
    - name: "openai/gpt-5.1-codex-mini"
      display_name: "OpenAI: GPT-5.1-Codex-Mini"
    - name: "openai/o1"
      display_name: "OpenAI: o1"
    - name: "openai/o1-pro"
      display_name: "OpenAI: o1-pro"
    - name: "openai/o3"
      display_name: "OpenAI: o3"
    - name: "openai/o3-deep-research"
      display_name: "OpenAI: o3 Deep Research"
    - name: "openai/o3-pro"
      display_name: "OpenAI: o3 Pro"
    - name: "openai/o4-mini"
      display_name: "OpenAI: o4 Mini"
    - name: "openai/o4-mini-deep-research"
      display_name: "OpenAI: o4 Mini Deep Research"
    - name: "openai/o4-mini-high"
      display_name: "OpenAI: o4 Mini High"
    - name: "opengvlab/internvl3-78b"
      display_name: "OpenGVLab: InternVL3 78B"
    - name: "perplexity/sonar"
      display_name: "Perplexity: Sonar"
    - name: "perplexity/sonar-pro"
      display_name: "Perplexity: Sonar Pro"
    - name: "perplexity/sonar-pro-search"
      display_name: "Perplexity: Sonar Pro Search"
    - name: "perplexity/sonar-reasoning-pro"
      display_name: "Perplexity: Sonar Reasoning Pro"
    - name: "qwen/qwen-vl-max"
      display_name: "Qwen: Qwen VL Max"
    - name: "qwen/qwen-vl-plus"
      display_name: "Qwen: Qwen VL Plus"
    - name: "qwen/qwen2.5-vl-32b-instruct"
      display_name: "Qwen: Qwen2.5 VL 32B Instruct"
    - name: "qwen/qwen2.5-vl-72b-instruct"
      display_name: "Qwen: Qwen2.5 VL 72B Instruct"
    - name: "qwen/qwen-2.5-vl-7b-instruct"
      display_name: "Qwen: Qwen2.5-VL 7B Instruct"
    - name: "qwen/qwen3-vl-235b-a22b-instruct"
      display_name: "Qwen: Qwen3 VL 235B A22B Instruct"
    - name: "qwen/qwen3-vl-235b-a22b-thinking"
      display_name: "Qwen: Qwen3 VL 235B A22B Thinking"
    - name: "qwen/qwen3-vl-30b-a3b-instruct"
      display_name: "Qwen: Qwen3 VL 30B A3B Instruct"
    - name: "qwen/qwen3-vl-30b-a3b-thinking"
      display_name: "Qwen: Qwen3 VL 30B A3B Thinking"
    - name: "qwen/qwen3-vl-8b-instruct"
      display_name: "Qwen: Qwen3 VL 8B Instruct"
    - name: "qwen/qwen3-vl-8b-thinking"
      display_name: "Qwen: Qwen3 VL 8B Thinking"
    - name: "stepfun-ai/step3"
      display_name: "StepFun: Step3"
    - name: "thudm/glm-4.1v-9b-thinking"
      display_name: "THUDM: GLM 4.1V 9B Thinking"
    - name: "z-ai/glm-4.5v"
      display_name: "Z.AI: GLM 4.5V"
    - name: "x-ai/grok-4"
      display_name: "xAI: Grok 4"
    - name: "x-ai/grok-4-fast"
      display_name: "xAI: Grok 4 Fast"
    - name: "x-ai/grok-4.1-fast:free"
      display_name: "xAI: Grok 4.1 Fast (free)"
app:
  title: Image-to-Text Demo
  version: "0.1.0"

