model:
  name: Qwen3-VL-8B-Instruct
  base_url: 
  api_key: ""
  default_prompt: "请根据提供的网页设计图，编写对应的HTML代码，将结果写在一个 markdown HTML 代码块中"
  allowed_mime_types:
    - image/png
    - image/jpeg
    - image/svg+xml
  sampling_args:
    temperature: 0.7
    top_p: 0.8
    presence_penalty: 1.5
    max_completion_tokens: 16384
  extra_args:
    top_k: 20
    repetition_penalty: 1.0

app:
  title: Image-to-Text Demo
  version: "0.1.0"

